name: Check 和 Merge READMEs

on:
  schedule:
    - cron: '0 8 * * *'  # 每天8点触发
  workflow_dispatch:
    inputs:
      rebuild:
        description: '忽略构建记录以重新构建'
        required: false
        type: boolean
      donotpublish:
        description: '构建后不提交发布新版'
        required: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - userName: xisohi
            repoName: IPTVbox
            branchName: main
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check New Commit
        id: check_commit
        run: |
          # 获取最新提交的SHA值
          latestCommit=$(curl -sL "https://api.github.com/repos/${{  matrix.userName }}/${{ matrix.repoName }}/commits/${{ matrix.branchName }}" | jq -r '.sha')
          echo "latestCommit=$latestCommit" >> $GITHUB_ENV

      - name: Check secondLastCommitSHA
        id: check_secondLastCommitSHA
        run: |
          # 获取倒数第二次提交的SHA值，并检查倒数第二次提交的SHA值是否在 README.md 文件中，如要在就退出，不在就执行剩余代码
          commit=$(curl -sL "https://api.github.com/repos/${{ matrix.userName }}/${{ matrix.repoName }}/commits/${{ matrix.branchName }}" | jq -r '.parents[0].sha')
          if [ $? -ne 0 ]; then
            echo "Failed to get commit from API"
            exit 1
          fi
          if [ -z "$commit" ] || ! grep -q "$commit" README.md; then
            echo "commit=$commit" >> $GITHUB_ENV
            echo "commitS=${commit:0:7}" >> $GITHUB_ENV
          fi
      - name: Merge READMEs if there are new commits
        if: ${{ env.commit }}
        run: |
          # 合并文件目录中README.md内容，并追加最新提交的SHA值，
          directories=("中兴" "九联" "创维" "华为" "海信" "烽火" "魔百和" "歌华有线")
          merged_file="/tmp/merged_readme.md"
          > "$merged_file"

          for dir in "${directories[@]}"; do
            readme_file="${dir}/README.md"
            if [ -f "$readme_file" ]; then
              cat "$readme_file" >> "$merged_file"
              echo -e "\n" >> "$merged_file"
            else
              echo "Warning: $readme_file does not exist. Skipping."
            fi
          done

          mv "$merged_file" README.md
          latestCommit=${{ env.latestCommit }}
          echo -e "\n最新提交的SHA值: $latestCommit" >> README.md

          # 复制 README.md 文件到 index.html
          cp README.md index.html 
          
          # 使用 sed 在文件中添加 CSS 样式
          css_styles='<style>
          table { width: 100%; border-collapse: collapse; }
          th, td { border: 1px solid #000; padding: 8px; text-align: left; }
          th { background-color: #f2f2f2; }
          </style>'
          awk -v css="$css_styles" 'BEGIN {print css} {print}' index.html > temp && mv temp index.html

      - name: Commit and Push Changes
        if: ${{ env.commit }}
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md index.html
          git commit -m "Merge READMEs from subdirectories and append second last commit SHA"
          git push
